### ISSUE TITLE
Failing on keys that start with 'o'

### ISSUE THREAD

**Issue by jcdeoferio** [Berkmann18/json-fixer#38]
## How to reproduce

Test Data: `{ o: 1 }`

Seems to fail with any key as long as it starts with the lower case `o`.

Using an array, object, string or boolean as the value doesn't seem to have any difference, it fails regardless of the value.

Stacktrace:
```
There's still an error!
Error encountered Error: Expected "}" or string but "o" found.
    at doubleCheck (\node_modules\json-fixer\index.js:31:11)
    at fixJson (\node_modules\json-fixer\index.js:99:10)
    at doubleCheck (\node_modules\json-fixer\index.js:29:44)
    at fixJson (\node_modules\json-fixer\index.js:99:10)
    at doubleCheck (\node_modules\json-fixer\index.js:29:44)
    at fixJson (\node_modules\json-fixer\index.js:99:10)
    at doubleCheck (\node_modules\json-fixer\index.js:29:44)
    at fixJson (\node_modules\json-fixer\index.js:99:10)
    at doubleCheck (\node_modules\json-fixer\index.js:29:44)
    at fixJson (\node_modules\json-fixer\index.js:99:10)
```

## Environment

- Version: 1.4.3
- OS(s): Win10 x64 1903
- Browser(s) (if applicable):
- Node version: 12.18.0
- NPM version: 6.14.4

**Comment by Berkmann18** [comment]
Thanks for reporting this issue, I've taken note of it and will look into it when I can.
PRs are welcome!
